(100, 'Some error')
MyExc(100, 'Some error')
(100, 'Some error')
Caught exception: MyExc('Some error', 1)
Caught exception: MyExc('Some error2', 2)
Caught user exception
